# Generated by Django 5.0 on 2023-12-12 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_alter_user_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportperson',
            old_name='phone_no',
            new_name='phone_number',
        ),
    ]
