# Generated by Django 5.0 on 2023-12-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_rename_phone_no_supportperson_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportperson',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='supportperson',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='supportperson',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='supportperson',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='supportperson',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
    ]
